/*
 * To change this license header, choose License Headers in Project Properties.
 * To change this template file, choose Tools | Templates
 * and open the template in the editor.
 */
package view;

/**
 *
 * @author Pichau
 */
public class Tela extends javax.swing.JFrame {

    /**
     * Creates new form Tela
     */
    public Tela() {
        initComponents();
    }

    /**
     * This method is called from within the constructor to initialize the form.
     * WARNING: Do NOT modify this code. The content of this method is always
     * regenerated by the Form Editor.
     */
    @SuppressWarnings("unchecked")
    // <editor-fold defaultstate="collapsed" desc="Generated Code">//GEN-BEGIN:initComponents
    private void initComponents() {

        pnTitulo = new javax.swing.JPanel();
        jLabel1 = new javax.swing.JLabel();
        pnBotoes = new javax.swing.JPanel();
        btCancelar = new javax.swing.JButton();
        btLimpar = new javax.swing.JButton();
        btSalvar = new javax.swing.JButton();
        pnMenu = new javax.swing.JPanel();
        btClientes = new javax.swing.JButton();
        btFornecedores = new javax.swing.JButton();
        btProdutos = new javax.swing.JButton();
        btEntrada = new javax.swing.JButton();
        btSaida = new javax.swing.JButton();
        pnCentral = new javax.swing.JPanel();
        lbClientes = new javax.swing.JLabel();
        lbCelular = new javax.swing.JLabel();
        lbEmail = new javax.swing.JLabel();
        txtNome = new javax.swing.JTextField();
        txtCpf = new javax.swing.JTextField();
        txtCelular = new javax.swing.JTextField();
        txtEmail = new javax.swing.JTextField();
        lbCpf = new javax.swing.JLabel();
        lbNome = new javax.swing.JLabel();

        setDefaultCloseOperation(javax.swing.WindowConstants.EXIT_ON_CLOSE);

        pnTitulo.setBackground(new java.awt.Color(235, 235, 235));
        pnTitulo.setLayout(new org.netbeans.lib.awtextra.AbsoluteLayout());

        jLabel1.setBackground(new java.awt.Color(204, 204, 204));
        jLabel1.setFont(new java.awt.Font("Century Gothic", 0, 48)); // NOI18N
        jLabel1.setHorizontalAlignment(javax.swing.SwingConstants.CENTER);
        jLabel1.setText("Kardex");
        pnTitulo.add(jLabel1, new org.netbeans.lib.awtextra.AbsoluteConstraints(-3, 0, 780, -1));

        getContentPane().add(pnTitulo, java.awt.BorderLayout.NORTH);

        pnBotoes.setLayout(new java.awt.GridLayout());

        btCancelar.setText("Cancelar");
        pnBotoes.add(btCancelar);

        btLimpar.setText("Limpar");
        pnBotoes.add(btLimpar);

        btSalvar.setText("Salvar");
        pnBotoes.add(btSalvar);

        getContentPane().add(pnBotoes, java.awt.BorderLayout.SOUTH);

        pnMenu.setBackground(new java.awt.Color(230, 230, 230));
        pnMenu.setLayout(new javax.swing.BoxLayout(pnMenu, javax.swing.BoxLayout.PAGE_AXIS));

        btClientes.setFont(new java.awt.Font("Century Gothic", 1, 18)); // NOI18N
        btClientes.setText("Clientes");
        btClientes.setBorderPainted(false);
        btClientes.setContentAreaFilled(false);
        btClientes.setMaximumSize(new java.awt.Dimension(157, 31));
        btClientes.setMinimumSize(new java.awt.Dimension(157, 31));
        btClientes.setOpaque(false);
        btClientes.setPreferredSize(new java.awt.Dimension(157, 31));
        pnMenu.add(btClientes);

        btFornecedores.setFont(new java.awt.Font("Century Gothic", 1, 18)); // NOI18N
        btFornecedores.setText("Fornecedores");
        btFornecedores.setBorderPainted(false);
        btFornecedores.setContentAreaFilled(false);
        pnMenu.add(btFornecedores);

        btProdutos.setFont(new java.awt.Font("Century Gothic", 1, 18)); // NOI18N
        btProdutos.setText("Produtos");
        btProdutos.setBorderPainted(false);
        btProdutos.setContentAreaFilled(false);
        btProdutos.setMaximumSize(new java.awt.Dimension(157, 31));
        btProdutos.setMinimumSize(new java.awt.Dimension(157, 31));
        btProdutos.setPreferredSize(new java.awt.Dimension(157, 31));
        pnMenu.add(btProdutos);

        btEntrada.setFont(new java.awt.Font("Century Gothic", 1, 18)); // NOI18N
        btEntrada.setText("Entrada");
        btEntrada.setBorderPainted(false);
        btEntrada.setContentAreaFilled(false);
        btEntrada.setMaximumSize(new java.awt.Dimension(157, 31));
        btEntrada.setMinimumSize(new java.awt.Dimension(157, 31));
        btEntrada.setName(""); // NOI18N
        btEntrada.setPreferredSize(new java.awt.Dimension(157, 31));
        pnMenu.add(btEntrada);

        btSaida.setFont(new java.awt.Font("Century Gothic", 1, 18)); // NOI18N
        btSaida.setText("Saída");
        btSaida.setBorderPainted(false);
        btSaida.setContentAreaFilled(false);
        btSaida.setMaximumSize(new java.awt.Dimension(157, 31));
        btSaida.setMinimumSize(new java.awt.Dimension(157, 31));
        btSaida.setPreferredSize(new java.awt.Dimension(157, 31));
        pnMenu.add(btSaida);

        getContentPane().add(pnMenu, java.awt.BorderLayout.WEST);

        pnCentral.setBackground(new java.awt.Color(242, 242, 242));

        lbClientes.setFont(new java.awt.Font("Century Gothic", 0, 24)); // NOI18N
        lbClientes.setHorizontalAlignment(javax.swing.SwingConstants.CENTER);
        lbClientes.setText("Clientes");

        lbCelular.setText("Celular:");

        lbEmail.setText("E-mail:");

        lbCpf.setHorizontalAlignment(javax.swing.SwingConstants.CENTER);
        lbCpf.setText("CPF:");
        lbCpf.setHorizontalTextPosition(javax.swing.SwingConstants.CENTER);

        lbNome.setText("Nome:");

        javax.swing.GroupLayout pnCentralLayout = new javax.swing.GroupLayout(pnCentral);
        pnCentral.setLayout(pnCentralLayout);
        pnCentralLayout.setHorizontalGroup(
            pnCentralLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(pnCentralLayout.createSequentialGroup()
                .addGap(110, 110, 110)
                .addGroup(pnCentralLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addComponent(lbNome)
                    .addComponent(lbCpf)
                    .addComponent(lbCelular)
                    .addComponent(lbEmail))
                .addGap(26, 26, 26)
                .addGroup(pnCentralLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING, false)
                    .addComponent(txtNome)
                    .addComponent(txtCpf, javax.swing.GroupLayout.PREFERRED_SIZE, 116, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(txtCelular, javax.swing.GroupLayout.PREFERRED_SIZE, 90, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(txtEmail, javax.swing.GroupLayout.DEFAULT_SIZE, 348, Short.MAX_VALUE))
                .addGap(100, 100, Short.MAX_VALUE))
            .addComponent(lbClientes, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
        );
        pnCentralLayout.setVerticalGroup(
            pnCentralLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(pnCentralLayout.createSequentialGroup()
                .addGap(37, 37, 37)
                .addComponent(lbClientes)
                .addGap(29, 29, 29)
                .addGroup(pnCentralLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(txtNome, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(lbNome))
                .addGap(18, 18, 18)
                .addGroup(pnCentralLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(lbCpf)
                    .addComponent(txtCpf, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE))
                .addGap(18, 18, 18)
                .addGroup(pnCentralLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(lbCelular)
                    .addComponent(txtCelular, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE))
                .addGap(18, 18, 18)
                .addGroup(pnCentralLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(lbEmail)
                    .addComponent(txtEmail, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE))
                .addContainerGap(100, Short.MAX_VALUE))
        );

        getContentPane().add(pnCentral, java.awt.BorderLayout.CENTER);

        pack();
    }// </editor-fold>//GEN-END:initComponents

    /**
     * @param args the command line arguments
     */
    public static void main(String args[]) {
        /* Set the Nimbus look and feel */
        //<editor-fold defaultstate="collapsed" desc=" Look and feel setting code (optional) ">
        /* If Nimbus (introduced in Java SE 6) is not available, stay with the default look and feel.
         * For details see http://download.oracle.com/javase/tutorial/uiswing/lookandfeel/plaf.html 
         */
        try {
            for (javax.swing.UIManager.LookAndFeelInfo info : javax.swing.UIManager.getInstalledLookAndFeels()) {
                if ("Nimbus".equals(info.getName())) {
                    javax.swing.UIManager.setLookAndFeel(info.getClassName());
                    break;
                }
            }
        } catch (ClassNotFoundException ex) {
            java.util.logging.Logger.getLogger(Tela.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (InstantiationException ex) {
            java.util.logging.Logger.getLogger(Tela.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (IllegalAccessException ex) {
            java.util.logging.Logger.getLogger(Tela.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (javax.swing.UnsupportedLookAndFeelException ex) {
            java.util.logging.Logger.getLogger(Tela.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        }
        //</editor-fold>

        /* Create and display the form */
        java.awt.EventQueue.invokeLater(new Runnable() {
            public void run() {
                new Tela().setVisible(true);
            }
        });
    }

    // Variables declaration - do not modify//GEN-BEGIN:variables
    private javax.swing.JButton btCancelar;
    private javax.swing.JButton btClientes;
    private javax.swing.JButton btEntrada;
    private javax.swing.JButton btFornecedores;
    private javax.swing.JButton btLimpar;
    private javax.swing.JButton btProdutos;
    private javax.swing.JButton btSaida;
    private javax.swing.JButton btSalvar;
    private javax.swing.JLabel jLabel1;
    private javax.swing.JLabel lbCelular;
    private javax.swing.JLabel lbClientes;
    private javax.swing.JLabel lbCpf;
    private javax.swing.JLabel lbEmail;
    private javax.swing.JLabel lbNome;
    private javax.swing.JPanel pnBotoes;
    private javax.swing.JPanel pnCentral;
    private javax.swing.JPanel pnMenu;
    private javax.swing.JPanel pnTitulo;
    private javax.swing.JTextField txtCelular;
    private javax.swing.JTextField txtCpf;
    private javax.swing.JTextField txtEmail;
    private javax.swing.JTextField txtNome;
    // End of variables declaration//GEN-END:variables
}
